### ISSUE TITLE
您好我想请问一下那个流程图（excalidraw？）的手写字体是啥呀

### ISSUE THREAD

**Issue by LeonX86** [JimLiu/gpt-games#2]
![image](https://github.com/JimLiu/gpt-games/assets/49100008/90ea0e27-5c4e-447e-b96c-6a4e3fa1bb93)
这个字体

**Comment by LeonX86** [comment]
啊，我找到了，好像是跟这个网站中的字体一样的https://ajietextd.github.io/
找到了但是不敢用了QAQ
我从网页中提取出字体chinese.woff2然后转换格式成TTF
![image](https://github.com/JimLiu/gpt-games/assets/49100008/9bb9142b-8d15-4bfe-9341-5a637fb080b6)
![image](https://github.com/JimLiu/gpt-games/assets/49100008/e73dbb1f-bae4-4928-b20d-21b58488ac55)
来自知乎https://www.zhihu.com/question/423594906

**Comment by JimLiu** [comment]
字语青梅硬笔

**Comment by LeonX86** [comment]
> 字语青梅硬笔

谢谢，这个字体很好看
